name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
           login-server: ${{ secrets.REGIS_SERVER }}
           username: ${{ secrets.RESIG_USERNAME }}
           password: ${{ secrets.RESIG_PASSWORD }}
      - run: |
          docker build . -t "${{ secrets.REGIS_SERVER }}/DeleteMe_LE_Ju0:${{ github.sha }}"
          docker push "${{ secrets.REGIS_SERVER }}/DeleteMe_LE_Ju0:${{ github.sha }}"
